services:

  parking-spot:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - parking_db

  parking_db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parking-spot

  volumes:
    postgres_data: